DROP TABLE IF EXISTS docs;

CREATE TABLE docs (
  id    INTEGER PRIMARY KEY,
  name  TEXT    NOT NULL,
  text  TEXT    NOT NULL,
  lat   FLOAT8  NOT NULL,
  long  FLOAT8  NOT NULL
);

INSERT INTO docs (id, name, text, lat, long) VALUES
(1,   'Lodhi Garden',                      'Tranquil park with ancient tombs ideal for serene morning walks and cycling',                                          28.5931,   77.2197),
(2,   'Sanjay Van',                         'Dense forested trail hushed and undisturbed perfect for quiet nature walks',                                           28.5530,   77.1833),
(3,   'Nehru Park',                          'Calm and serene garden great for peaceful morning strolls on weekdays',                                                28.5990,   77.1985),
(4,   'Deer Park',                           'Secluded park with deer and birds tranquil and undisturbed throughout the day',                                        28.5541,   77.2016),
(5,   'Garden of Five Senses',               'Artistic garden with sculptures serene ambiance and calm pathways',                                                    28.5135,   77.2060),
(6,   'Qutub Minar',                         'Bustling UNESCO heritage tower teeming with tourists and school groups all day',                                       28.5244,   77.1855),
(7,   'Red Fort',                            'Vibrant historical monument packed with visitors and lively cultural events on weekends',                              28.6562,   77.2410),
(8,   'India Gate',                          'Lively open lawn buzzing with energetic families and street vendors every evening',                                    28.6129,   77.2295),
(9,   'Hauz Khas Village',                   'Buzzing nightlife hub packed with trendy cafes and energetic crowds at night',                                         28.5535,   77.2032),
(10,  'Connaught Place',                     'Bustling commercial centre teeming with shoppers tourists and vibrant street performers',                              28.6304,   77.2177),
(11,  'Golden Temple',                       'Serene spiritual sanctuary hushed atmosphere of devotion calm reflective pool and quiet prayers',                      31.6200,   74.8765),
(12,  'Taj Mahal',                           'Touristy wonder packed with visitors at all hours vibrant photo stops and guided tours',                               27.1751,   78.0421),
(13,  'Meenakshi Temple',                    'Vibrant Hindu temple energetic with rituals lively chants and bustling pilgrims',                                       9.9195,   78.1194),
(14,  'Amber Fort',                          'Packed heritage fort touristy mornings with energetic elephant rides and lively guides',                               26.9855,   75.8513),
(15,  'Marine Drive',                        'Tranquil seaside promenade calm at dawn serene ocean views and undisturbed walks',                                     18.9438,   72.8236),
(16,  'British Library',                     'Hushed research sanctuary calm reading rooms serene manuscripts and quiet scholars',                                    51.5296,   -0.1270),
(17,  'New York Public Library',             'Serene marble reading halls tranquil study spaces and hushed scholarly atmosphere',                                    40.7532,  -73.9822),
(18,  'Library of Congress',                 'Tranquil grand reading room hushed and undisturbed surrounded by historic collections',                                38.8887,  -77.0047),
(19,  'Trinity College Library',             'Hushed ancient hall undisturbed medieval manuscripts and serene scholarly silence',                                    53.3440,   -6.2546),
(20,  'Bibliothèque nationale de France',    'Calm historic archive peaceful study spaces and serene reading rooms',                                                 48.8333,    2.3497),
(21,  'Georgia Aquarium',                    'Vibrant marine exhibits teeming with families energetic whale shark tunnels and lively displays',                      33.7634,  -84.3951),
(22,  'Monterey Bay Aquarium',               'Bustling coastal attraction packed halls and lively sea otter feeding sessions',                                       36.6185, -121.9018),
(23,  'Sydney Sea Life Aquarium',            'Lively marine experience energetic shark dives and vibrant penguin encounters',                                       -33.8698,  151.2016),
(24,  'Osaka Aquarium Kaiyukan',             'Packed marine wonder vibrant whale shark displays and energetic underwater tunnel',                                    34.6543,  135.4290),
(25,  'Two Oceans Aquarium',                 'Lively ocean exhibits energetic penguin feedings and vibrant predator tank shows',                                    -33.9062,   18.4190),
(26,  'Sydney Opera House',                  'Iconic vibrant performing arts venue bustling with theatre goers and energetic cultural events',                      -33.8568,  151.2153),
(27,  'Vienna State Opera',                  'Grand classical concert hall elegant and packed on performance nights vibrant with music lovers',                      48.2030,   16.3695),
(28,  'La Scala',                            'Prestigious opera house packed for world-class performances and vibrant standing ovations',                            45.4674,    9.1895),
(29,  'Metropolitan Opera',                  'Vibrant cultural institution energetic evening performances and bustling Lincoln Center crowds',                       40.7726,  -73.9832),
(30,  'Royal Opera House',                   'Elegant and lively performance venue packed on opera nights and buzzing with anticipation',                            51.5129,   -0.1224),
(31,  'Wembley Stadium',                     'Massive football arena teeming with passionate chanting fans energetic and deafening on match days',                   51.5560,   -0.2796),
(32,  'Camp Nou',                            'Vibrant football cathedral packed with energetic Barça supporters and electric stadium atmosphere',                    41.3809,    2.1228),
(33,  'Melbourne Cricket Ground',            'Buzzing sports arena packed on cricket and AFL match days with energetic and roaring crowd',                         -37.8200,  144.9834),
(34,  'Eden Gardens',                        'Vibrant cricket stadium energetic crowd atmosphere and passionate roaring fans',                                       22.5646,   88.3433),
(35,  'Maracanã Stadium',                    'Legendary football venue teeming with electric fans vibrant carnival spirit and deafening roars',                    -22.9121,  -43.2302),
(36,  'Angkor Wat',                          'Serene ancient temple complex tranquil at dawn undisturbed stone galleries and peaceful moat',                        13.4125,  103.8670),
(37,  'Borobudur',                           'Peaceful Buddhist monument calm misty mornings hushed stupas and serene mountain backdrop',                            -7.6079,  110.2038),
(38,  'Shwedagon Pagoda',                    'Serene golden stupa tranquil spiritual atmosphere hushed devotees and calm incense rituals',                           16.7986,   96.1493),
(39,  'Prambanan Temple',                    'Hushed Hindu complex undisturbed ancient spires and serene forested archaeological zone',                              -7.7520,  110.4914),
(40,  'Fushimi Inari Shrine',                'Tranquil forest shrine path serene evening walks hushed bamboo groves and undisturbed torii gates',                   34.9671,  135.7727),
(41,  'Bondi Beach',                         'Vibrant surf beach packed with swimmers sunbathers and energetic beach volleyball players',                           -33.8908,  151.2743),
(42,  'Copacabana Beach',                    'Lively energetic beach teeming with volleyball games samba rhythms and vibrant street vendors',                       -22.9714,  -43.1823),
(43,  'Nusa Dua Beach',                      'Serene private beach resort tranquil and undisturbed with calm turquoise lagoon waters',                               -8.8004,  115.2316),
(44,  'Railay Beach',                        'Secluded limestone bay calm and peaceful accessible only by boat hushed jungle surroundings',                           8.0121,   98.8380),
(45,  'Anse Source d''Argent',               'Tranquil granite boulder beach serene and quiet with calm shallow waters and undisturbed solitude',                    -4.3618,   55.8427),
(46,  'Zermatt',                             'Tranquil alpine village serene mountain views hushed glacier trails and undisturbed skiing slopes',                    46.0207,    7.7491),
(47,  'Annapurna Base Camp',                 'Hushed Himalayan trail undisturbed natural solitude serene mountain panoramas and calm teahouses',                    28.5300,   83.8778),
(48,  'Torres del Paine',                    'Secluded Patagonian wilderness calm windswept landscapes tranquil glaciers and undisturbed trails',                   -50.9423,  -73.4068),
(49,  'Mount Fuji',                          'Peaceful volcanic summit tranquil at dawn hushed pilgrimage path and serene crater views',                             35.3606,  138.7274),
(50,  'Banff National Park',                 'Serene mountain wilderness calm turquoise lakes undisturbed wildlife and tranquil pine forests',                       51.4968, -115.9281),
(51,  'Louvre Museum',                       'Vibrant world-famous gallery packed with art enthusiasts bustling queues and energetic tour groups',                   48.8606,    2.3376),
(52,  'British Museum',                      'Bustling cultural institution teeming with global visitors lively guided tours and energetic school trips',             51.5194,   -0.1270),
(53,  'MoMA New York',                       'Lively modern art destination energetic and vibrant with design lovers and creative installations',                    40.7614,  -73.9776),
(54,  'Uffizi Gallery',                      'Packed Renaissance masterpiece collection touristy halls vibrant with art pilgrims and enthusiasts',                   43.7677,   11.2553),
(55,  'National Museum of India',            'Hushed historical collection calm and undisturbed serene galleries and tranquil sculpture courts',                     28.6117,   77.2196),
(56,  'Central Park',                        'Vibrant urban oasis energetic morning joggers lively picnics and bustling playgrounds on weekends',                   40.7851,  -73.9683),
(57,  'Hyde Park',                           'Tranquil open green space peaceful afternoon strolls serene boating lake and calm meadows',                            51.5074,   -0.1657),
(58,  'Yoyogi Park',                         'Serene weekend retreat calm and hushed on weekdays tranquil forested paths and quiet picnic spots',                    35.6715,  139.6944),
(59,  'Tiergarten',                          'Tranquil forested park peaceful cycling paths serene woodland glades and undisturbed morning walks',                   52.5145,   13.3501),
(60,  'Parc de la Villette',                 'Lively cultural park vibrant with events energetic skateboarding and bustling open-air concerts',                      48.8937,    2.3900),
(61,  'Colosseum',                           'Bustling ancient arena packed with tourists vibrant history and energetic guided tours year round',                    41.8902,   12.4922),
(62,  'Machu Picchu',                        'Serene Inca citadel tranquil at sunrise before the vibrant tourist crowds arrive later',                              -13.1631,  -72.5450),
(63,  'Petra',                               'Ancient rose city hushed at early morning tranquil canyon walk and undisturbed carved facades',                        30.3285,   35.4444),
(64,  'Acropolis',                           'Iconic hilltop ruins packed with visitors and vibrant with energetic tour groups in summer',                           37.9715,   23.7257),
(65,  'Chichen Itza',                        'Vibrant Mayan pyramid teeming with tourists energetic vendors and lively cultural performances',                       20.6843,  -88.5678),
(66,  'Café Central Vienna',                 'Elegant historic café calm and unhurried serene marble interiors and tranquil coffee rituals',                         48.2100,   16.3660),
(67,  'Café de Flore',                       'Iconic Parisian literary café lively and bustling with intellectuals vibrant and energetic atmosphere',                48.8539,    2.3332),
(68,  'Blue Bottle Coffee Tokyo',            'Serene minimalist café hushed and tranquil calm pour-over ritual and undisturbed tasting experience',                  35.6586,  139.7088),
(69,  'Intelligentsia Coffee Los Angeles',   'Calm specialty café tranquil and undisturbed serene barista craft and peaceful morning atmosphere',                    34.0930, -118.3621),
(70,  'Café Tortoni Buenos Aires',           'Historic café lively and vibrant with tango culture energetic live music and bustling after-dinner crowds',           -34.6041,  -58.3747),
(71,  'University of Oxford',                'Serene academic grounds hushed cloisters tranquil quads and undisturbed medieval corridors',                           51.7548,   -1.2544),
(72,  'Harvard Yard',                        'Tranquil collegiate green calm and undisturbed hushed pathways and serene historic red-brick buildings',               42.3744,  -71.1169),
(73,  'IIT Delhi Campus',                    'Serene tree-lined academic campus peaceful lecture halls calm and undisturbed green quadrangles',                      28.5459,   77.1926),
(74,  'University of Melbourne',             'Calm urban campus tranquil gardens and peaceful pathways hushed reading rooms',                                       -37.7963,  144.9614),
(75,  'ETH Zurich Campus',                   'Hushed academic institution serene and focused atmosphere calm laboratory corridors and undisturbed courtyards',       47.3763,    8.5480),
(76,  'Venice Grand Canal',                  'Vibrant and bustling waterway teeming with gondolas lively cafes and energetic tourist foot traffic',                  45.4371,   12.3326),
(77,  'Singapore Marina Bay',                'Energetic waterfront vibrant skyline buzzing with lively night events and teeming promenade crowds',                    1.2816,  103.8636),
(78,  'Hong Kong Victoria Harbour',          'Bustling harbour promenade teeming with ferry traffic and vibrant neon-lit evening activity',                          22.2942,  114.1700),
(79,  'Stockholm Old Town',                  'Tranquil cobblestone harbour hushed medieval lanes serene waterfront and undisturbed historic squares',                59.3249,   18.0712),
(80,  'Bruges Canal Walks',                  'Peaceful medieval waterways calm and undisturbed serene reflections and tranquil horse-drawn carriage routes',         51.2093,    3.2247),
(81,  'Black Forest Germany',                'Tranquil ancient woodland serene hiking trails hushed pine canopy and undisturbed forest streams',                     48.0000,    8.2000),
(82,  'Daintree Rainforest',                 'Serene tropical wilderness calm and peaceful hushed ancient ferns and undisturbed wildlife',                          -16.1700,  145.4200),
(83,  'Redwood National Park',               'Tranquil towering forests hushed cathedral groves undisturbed coastal trails and serene silence',                      41.2132, -124.0046),
(84,  'Sundarbans',                          'Secluded mangrove delta calm tiger reserve tranquil river channels and undisturbed wildlife sanctuary',                21.9497,   89.1833),
(85,  'Jiuzhaigou Valley',                   'Serene alpine lakes tranquil turquoise waters hushed forested valley and undisturbed Tibetan scenery',                 33.2600,  103.9200),
(86,  'Santorini',                           'Vibrant Mediterranean island packed with tourists energetic caldera viewpoints and lively rooftop bars',               36.3932,   25.4615),
(87,  'Maldives North Malé Atoll',           'Serene tropical paradise tranquil and undisturbed calm lagoon waters and peaceful overwater bungalows',                4.1755,   73.5093),
(88,  'Faroe Islands',                       'Secluded dramatic cliffs hushed and peaceful undisturbed puffin colonies and tranquil highland hikes',                 62.0000,   -6.7900),
(89,  'Galápagos Islands',                   'Tranquil wildlife sanctuary calm and undisturbed serene sea lion beaches and hushed lava fields',                      -0.9538,  -90.9656),
(90,  'Bora Bora',                           'Serene lagoon paradise peaceful and quiet tranquil snorkelling and undisturbed coral gardens',                        -16.5004, -151.7415),
(91,  'Marrakech Medina',                    'Vibrant bustling souk teeming with vendors energetic aromas lively bargaining and packed alleyways',                   31.6295,   -7.9811),
(92,  'Bangkok Chatuchak Market',            'Lively and energetic weekend market teeming with shoppers vibrant street food and buzzing stalls',                     13.7999,  100.5500),
(93,  'Chandni Chowk Delhi',                 'Bustling historic bazaar teeming and chaotic energetic spice merchants and vibrant street food',                       28.6506,   77.2300),
(94,  'Grand Bazaar Istanbul',               'Vibrant ancient market packed with traders and tourists energetic haggling and bustling corridors',                    41.0108,   28.9681),
(95,  'Tsukiji Outer Market Tokyo',          'Bustling seafood market teeming with vendors lively sushi stalls and energetic early morning activity',                35.6654,  139.7707),
(96,  'Keukenhof Gardens',                   'Vibrant tulip fields lively with spring visitors and energetic flower festivals',                                       52.2697,    4.5469),
(97,  'Kenrokuen Garden',                    'Serene traditional Japanese garden tranquil and hushed peaceful stone lanterns and calm snow-covered paths',           36.5613,  136.6622),
(98,  'Kirstenbosch Botanical Garden',       'Peaceful Cape floral kingdom calm and undisturbed serene fynbos trails and tranquil mountain backdrop',               -33.9883,   18.4328),
(99,  'Royal Botanic Gardens Kew',           'Tranquil Victorian glasshouses serene afternoon strolls undisturbed herbarium and calm riverside meadows',             51.4787,   -0.2956),
(100, 'Generalife Gardens Granada',          'Calm Moorish water garden hushed and peaceful serene fountain courtyards and undisturbed terraced greenery',           37.1773,   -3.5882),
(101, 'Humayun''s Tomb',                    'Serene Mughal garden tomb tranquil symmetrical pathways and hushed stone chambers',                                    28.5933,   77.2507),
(102, 'Purana Qila',                         'Calm ancient fort with peaceful boating lake undisturbed archaeological ruins and quiet ramparts',                     28.6075,   77.2427),
(103, 'National Zoological Park Delhi',      'Lively urban zoo bustling with families energetic animal shows and vibrant birdwatching',                              28.6004,   77.2447),
(104, 'Jantar Mantar Delhi',                 'Tranquil astronomical observatory hushed stone instruments and serene heritage courtyard',                              28.6270,   77.2165),
(105, 'Akshardham Temple',                   'Vibrant Hindu monument teeming with devotees energetic fountain shows and bustling evening ceremonies',                28.6127,   77.2773),
(106, 'Lotus Temple',                        'Serene Bahai house of worship tranquil meditation halls hushed and undisturbed open to all faiths',                    28.5535,   77.2588),
(107, 'Safdarjung Tomb',                     'Calm Mughal garden tomb serene and undisturbed peaceful lawns with very few visitors',                                 28.5907,   77.2079),
(108, 'Nizamuddin Dargah',                   'Serene Sufi shrine hushed devotional atmosphere tranquil qawwali evenings and calm incense courtyards',                28.5895,   77.2465),
(109, 'Dilli Haat INA',                      'Vibrant open-air craft bazaar bustling with artisans energetic folk performances and lively street food',              28.5722,   77.2100),
(110, 'Khan Market',                         'Bustling upscale market teeming with cafes bookshops and energetic weekend brunch crowds',                             28.5996,   77.2270),
(111, 'Tughlaqabad Fort',                    'Secluded ruined fort tranquil and undisturbed hushed massive ramparts and serene rocky wilderness',                    28.4891,   77.2578),
(112, 'Agrasen ki Baoli',                    'Tranquil ancient stepwell hushed and undisturbed serene hidden in the heart of the city',                              28.6267,   77.2197),
(113, 'Lajpat Nagar Market',                 'Bustling wholesale market teeming with shoppers vibrant fabric stalls and energetic street food vendors',              28.5700,   77.2429),
(114, 'Cyber Hub Gurgaon',                   'Vibrant dining and entertainment hub bustling with young professionals energetic live music and packed restaurants',   28.4946,   77.0886),
(115, 'Aravalli Biodiversity Park',          'Tranquil urban forest serene walking trails hushed native flora and undisturbed birdwatching zone',                    28.4780,   77.1023),
(116, 'Kingdom of Dreams Gurgaon',           'Vibrant live entertainment complex bustling with theatre goers energetic Bollywood shows and lively performances',     28.4944,   77.0733),
(117, 'Okhla Bird Sanctuary',                'Serene wetland reserve tranquil migratory birds hushed reeds and undisturbed peaceful riverside habitat',              28.5269,   77.3074),
(118, 'Kalindi Kunj Park',                   'Calm riverside park tranquil and undisturbed peaceful picnic spots along serene Yamuna banks',                         28.5389,   77.3108),
(119, 'Noida Sector 18 Market',              'Bustling commercial hub teeming with shops energetic food courts and vibrant evening shopping',                         28.5672,   77.3224),
(120, 'Iskcon Temple Delhi',                 'Serene Krishna temple tranquil devotional atmosphere hushed marble halls and calm spiritual gardens',                  28.5564,   77.2021),
(121, 'Mehrauli Archaeological Park',        'Secluded forested heritage zone tranquil ancient ruins undisturbed medieval tombs and calm wooded trails',             28.5154,   77.1855),
(122, 'Lodi Colony Flower Market',           'Vibrant early morning flower bazaar bustling with vendors lively colours and energetic wholesale trade',               28.5880,   77.2270),
(123, 'Bhuli Bhatiyari ka Mahal',            'Hushed ruined hunting lodge secluded inside Delhi Ridge forest undisturbed and tranquil',                              28.6507,   77.1571),
(124, 'Coronation Park Delhi',               'Calm historical park serene and undisturbed tranquil statues and peaceful open lawns',                                 28.7132,   77.1846),
(125, 'Delhi Ridge Forest',                  'Tranquil urban lung of Delhi hushed forested trails undisturbed wildlife and serene ancient rock formations',          28.6712,   77.1463);
